import type { Metadata } from 'next';
import AppProviders from '@/providers';
import { Container, CssBaseline } from '@mui/material';

export const metadata: Metadata = {
  title: 'Visum test',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppProviders>
          <CssBaseline />
          <Container sx={{ pt: 4 }}>{children}</Container>
        </AppProviders>
      </body>
    </html>
  );
}
